/**
 * Multiplay SDK Daemon Game Server API
 * The game server API is called by the Multiplay Game Server SDK itself to subscribe to events and report server status.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace Multiplay
{

/*
 * OpenAPIPayloadTokenResponseBody
 *
 * 
 */
class MULTIPLAYGAMESERVERSDK_API OpenAPIPayloadTokenResponseBody : public Model
{
public:
    virtual ~OpenAPIPayloadTokenResponseBody() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* JWT Token string associated to payload requests */
	FString Token;
	/* Internal multiplay error occurred retrieving the JWT */
	FString Error;
};

}
