/**
 * Multiplay SDK Daemon Game Server API
 * The game server API is called by the Multiplay Game Server SDK itself to subscribe to events and report server status.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace Multiplay
{

/*
 * OpenAPIPayloadAllocationErrorResponseBody
 *
 * 
 */
class MULTIPLAYGAMESERVERSDK_API OpenAPIPayloadAllocationErrorResponseBody : public Model
{
public:
    virtual ~OpenAPIPayloadAllocationErrorResponseBody() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* the call went through successfully */
	bool Success = false;
	/* there exists an error */
	bool Error = false;
	/* code of the error */
	int32 ErrorCode = 0;
	/* a message describing the error */
	FString ErrorMessage;
};

}
